swagger: "2.0"
info: 
  title: "tharun"
  version: "2.0.0"
  description: "tharun"
paths: 
  /tharun: 
    post: 
      operationId: "postTharun"
      responses: 
        200: 
          description: "The operation was successful."
      consumes: 
      - "application/json"
      produces: 
      - "application/json"
      description: "Insert a tharun"
      parameters: 
      - name: "body"
        in: "body"
        schema: 
          type: "string"
        description: "The request body for the operation"
        required: "true"
basePath: "/tharun/v1"
