swagger: "2.0"
info: 
  title: "balveer"
  version: "1.0.0"
  description: "balveer"
paths: 
  /balu: 
    post: 
      operationId: "postBalu"
      responses: 
        200: 
          description: "The operation was successful."
      consumes: 
      - "application/json"
      produces: 
      - "application/json"
      description: "Insert a balu"
      parameters: 
      - name: "body"
        in: "body"
        schema: 
          type: "string"
        description: "The request body for the operation"
        required: "true"
basePath: "/balveer/v1"
